### ISSUE TITLE
Safe views

### ISSUE THREAD

**Issue by raphaelcosta** [FlavourSaver/FlavourSaver#12]
Is it possible to implement safe views like Tache?
https://github.com/thelucid/tache/blob/master/lib/tache/safe.rb

**Comment by christiangenco** [comment]
Tache's safe views prevent you from being able to do this:

```ruby
template = Tilt['handlebars'].new { "Hello {{planet.inspect}}" }
data = OpenStruct.new planet: 'World'
template.render data
=> "Hello #&lt;FlavourSaver::Helpers::Decorator:0x007fe1ecccf4b8 @source=&quot;World&quot;&gt;"
```

This is done so templates can "be edited by end users, without the risk jeopardising your application's security...calls to potentially destructive methods such as 'eval' or 'destroy' are ignored." 

Though I'm not sure how you could get an `eval` from a template. In it's current state, are FlavourSaver templates safe to be edited by end users?
