### ISSUE TITLE
undefined method `[]' for nil:NilClass on calling render with empty params

### ISSUE THREAD

**Issue by igor-drozdov** [FlavourSaver/FlavourSaver#30]
To reproduce, try calling this:

``` ruby
  Tilt['handlebars'].new{'{{a.[0]}}'}.render
```

The error occurs, because `@source` in the following method is `nil`, but `:[]` method is tried to be called on it.

``` ruby
  def [](accessor)
    if array?
      if accessor.match /[0-9]+/
        return @source.at(accessor.to_i)
      end
    end
    @source[accessor]
  end
```

It can be checked explicitly, whether `@source` responds to `:[]`
`@source = source || {}` in the initializer could help too

What do you think?

**Comment by grumbleafrican** [comment]
A smaller change which should still follow the expected handlebars results (empty/nil) is as follows

```ruby
  def [](accessor)
    return if @source
    if array?
      if accessor.match /[0-9]+/
        return @source.at(accessor.to_i)
      end
    end
    @source[accessor]
  end
```
Can you provide a full test example? Or even better write an rspec.

**Comment by flexoid** [comment]
@igor-drozdov it's fixed now, feel free to try it out 😅

**Comment by igor-drozdov** [comment]
@flexoid Amazing! Thanks for the fix! 🤣
