### ISSUE TITLE
Inconsistency of IF helper with handlebars.js implementation.

### ISSUE THREAD

**Issue by undergroundwebdesigns** [FlavourSaver/FlavourSaver#38]
The handlebars.js implementation and [docs](http://handlebarsjs.com/builtin_helpers.html) define the `if` helper as not rendering the block if the argument returns `false`, `undefined`, `null`, `""`, `0`, or `[]`. The implementation of `if` in FlavourSaver however _will_ render the block if the argument is `""` or `0`, as both of these are "truthy" in Ruby. We're seeing issues with this as we're using handlebars templates that will be rendered both in Ruby and in our JS front-end app, and ideally the behaviour would be consistent.

Was this divergence intentional, and might it be fixed?

**Comment by grumbleafrican** [comment]
Sounds like an unintentional divergence.

**Comment by lucasprag** [comment]
I could work on this if that's ok 👍

**Comment by ClaytonPassmore** [comment]
Thanks @lucasprag! 🎉
