### ISSUE TITLE
Bug with mixing literal and hash arguments.

### ISSUE THREAD

**Issue by jimsynz** [FlavourSaver/FlavourSaver#6]
FlavourSaver is throwing a StringNotInLanguage exception when it comes across helpers called with a mixture of literal and hash arguments, for example:

``` handlebars
{{#linkTo "index" tagName="li"}}
  Home
{{/linkTo}}
```

Failing test committed in c19567c51c8adbdecf49fed28750b8e7d0916c7f (`args-bug` branch).

**Comment by bluegod** [comment]
Is there a workaround for this ? Not sure if is the same issue but when I have something like `{{method "blah" opts="test"}}`

I get the same exception. Debugging the plugin I can see that there is no "state" for :EQ

    0> @states[stack.state].on?(:EQ)
    => []

while that works for any other option:
    0> @states[stack.state].on?(:IDENT)
    => [#<RLTK::Parser::Reduce:0x0000010745c858 @id=66>]

**Comment by bluegod** [comment]
Took a while but I believe I fixed it. Made a PR #29

**Comment by jamesotron** [comment]
Thanks for all the hard work.  Yes, RLTK is more trouble than it's worth for this project - I'm considering replacing it with a racc based parser, but it hasn't reached the top of my list.

**Comment by ClaytonPassmore** [comment]
Looks like this fixed in #29, closing :+1:
